[functions]
  node_bundler="esbuild"

[build]
  command = "npm run build"
  publish = "dist"
  # base ="/"
  functions="src/functions"

[[redirects]]
  from="/*"
  to="/.netlify/functions/:splat"
  status=200