[functions]
  node_bundler="esbuild"
  included_files=["dist/data/**"]

[build]
  command = "npm run build"
  publish = "dist"
  # base ="/"
  functions="src/functions"

[[redirects]]
  from="/*"
  to="/.netlify/functions/server/:splat"
  status=200